### ISSUE TITLE
automatic wrapping of rlisting cols

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rlistings#116]
currently automatic wrapping is not enabled in rlistings.
Here we would like the wrapping to meet the following criteria:

if we are left-aligning the text, and the length is too long and need wrapping, the next line should be distinguishable, with two spaces indention.

```
MedDRA System Organ Class   MedDRA Preferred Term   Reported Term for the Adverse Event
———————————————————————————————————————————————————————————————————————————————————————
cl A.1                      dcd A.1.1.1.1                      ae term is...
                                                                 too long
                                                               normal length          
                            dcd A.1.1.1.2                      trm A.1.1.1.2           

```

otherwise we can't distinguish the term if it is a new entry or the same entry but wrapped

**Comment by Melkiades** [comment]
I think this is also possibly new development/feature bc it needs to modify behavior in comparison to rtables where this was specifically asked to be avoided (if I remember correctly)

**Comment by gmbecker** [comment]
Yes, the current behavior is to not do this, and that was an intention choice. Having tables and listings have different behaviors here is not desirable, so while a change to implement this actual behavior might not be difficult, fitting it within the framework and figuring out what to do more generally seems like it will be.

**Comment by clarkliming** [comment]
Column label and column contents are two different things, @barnett11 please help provide your comments here

**Comment by clarkliming** [comment]
See https://github.com/insightsengineering/sme-tasks/issues/619

**Comment by gmbecker** [comment]
@clarkliming in our meeting with @shajoezhu said we would not be pursuing this in the short term

**Comment by barnett11** [comment]
> Column label and column contents are two different things, @barnett11 please help provide your comments here

The original response was for table column displays, where it is maybe easier to distinguish new lines vs wrapped lines aas the summary statistics are shown against each appropriate record. 
This is different for listings, which is just independent text, and the current conventions used by STREAM is to wrap with indent listings so that they can distinguish new lines vs wrapped lines. An example from STREAM is below,

![image](https://github.com/insightsengineering/rlistings/assets/87320028/c1caeb1c-3744-4b14-a717-23a18c8f39a6)

**Comment by shajoezhu** [comment]
Hi Gabe

> @clarkliming in our meeting with @shajoezhu he said we would not be pursuing this in the short term

I think there are two topics here. We need to decouple the issue here. let's refine the issue a bit more.

**Comment by gmbecker** [comment]
@shajoezhu sorry, but there aren't really. Changing cell-content wrapping behavior is a large technical task which is also an explicit breaking change in rtables, because cell-content wrapping is implemented in formatters.

We do not currently have the ability to decouple rlistings and rtables wrapping behavior, and pursuing that would be extremely costly for  the size of the change in behavior  (and would represent major investment in rlistings development).

If we want the change in wrapping to happen accross the board, then that needs to be a longer term thing, because it is a breaking change in a much more established package (rtables)

**Comment by clarkliming** [comment]
we can skip this issue for now as there are work arounds to this issue. does not need to implement this for now.

**Comment by gmbecker** [comment]
I'm also going to mark this as blocked because it depends on #115, since indenting after wordwrap only makes sense if the text is left-aligned, not for center (or right) aligned.

Another note if we ever do come back to this, is that it only really makes sense for text. For word wrapping of multi-valued cells in a rtables table, for example, we wouldn't want indenting.

**Comment by shajoezhu** [comment]
aglined with Liming, that this will be addressed using data processing adding line breaks and spaces. closing this issue.
