### ISSUE TITLE
create unit test for repeated columns

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#30]
see the roadmap document "Repeated columns "

**Comment by edelarua** [comment]
@gmbecker when I run the following code to apply pagination I get an error:

```r
lsting <- as_listing(
    df = ex_adae,
    cols = c("ARM", "USUBJID", "AETOXGR", "AGE", "SEX", "RACE", "AEDECOD", "AESEV"),
    key_cols = c("ARM", "USUBJID", "AETOXGR")
)

paginate_listing(lsting, cpp = 4)
```
Error message:
```
Error in .local(obj, indent_rownames) : 
 indenting rownames is not supported for listings
```

Is this expected behaviour? I am able to get results when only vertical pagination is used (i.e. `cpp` unspecified).

**Comment by gmbecker** [comment]
> @gmbecker when I run the following code to apply pagination I get an error:
> 
> ```r
> lsting <- as_listing(
>     df = ex_adae,
>     cols = c("ARM", "USUBJID", "AETOXGR", "AGE", "SEX", "RACE", "AEDECOD", "AESEV"),
>     key_cols = c("ARM", "USUBJID", "AETOXGR")
> )
> 
> paginate_listing(lsting, cpp = 4)
> ```
> 
> Error message:
> 
> ```
> Error in .local(obj, indent_rownames) : 
>  indenting rownames is not supported for listings
> ```
> 
> Is this expected behaviour? I am able to get results when only vertical pagination is used (i.e. `cpp` unspecified).

No this is a bug.


> 
> This comes from the `vert_pag_indices` function in `paginate_listing` where `indent_rownames = TRUE` is set in the first line.

Yeah, I figured it was something like this. `indent_rownames = TRUE` is correct there, because we need the actual widths a table's row names will take up in order to do horizontal pagination (which again, is what the unfortunately named `vert_pag_indices` function does)

There are 2 possible fixes:

1. create the matrix form using `matrix_form(lsting, FALSE)` and then pass that (instead of `lsting`) to `vert_pag_indices`
2. make `matrix_form(<listing>, indent_rownames = TRUE)` just ...not indent anything (which is the "correct amount of indentation") rather than throwing an error.

Either way, I'll roll up the fix to this in with adding the page-size stuff to listing pagination.

**Comment by gmbecker** [comment]
Added blocked tag until the fix for above is in.

**Comment by edelarua** [comment]
@gmbecker I see that you have added unit tests for key columns into `test-paginate_listing.R` and all seems to be working now. Can this issue be closed, or are additional tests still needed?

**Comment by gmbecker** [comment]
@edelarua 

Its true that the pagination tests I added cover columns repeated when more than one column is a key column. Please add simple tests (only need to test display-column names, not full output) for 0-keycol and 1-keycol cases. One we have those this can be closed
